/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tugalsan.dsk.file.sync;

/**
 *
 * @author me
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        taConsole = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        tb = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnRunAll = new javax.swing.JButton();
        lblSrcDir1 = new javax.swing.JLabel();
        lblDstDir1 = new javax.swing.JLabel();
        tfDstDir1 = new javax.swing.JTextField();
        tfSrcDir1 = new javax.swing.JTextField();
        btnRecordSrcDir1 = new javax.swing.JButton();
        btnRecordDstDir1 = new javax.swing.JButton();
        btnRun1 = new javax.swing.JButton();
        lblSrcDir2 = new javax.swing.JLabel();
        lblDstDir2 = new javax.swing.JLabel();
        tfDstDir2 = new javax.swing.JTextField();
        tfSrcDir2 = new javax.swing.JTextField();
        btnRecordSrcDir2 = new javax.swing.JButton();
        btnRecordDstDir2 = new javax.swing.JButton();
        btnRun2 = new javax.swing.JButton();
        lblSrcDir3 = new javax.swing.JLabel();
        lblDstDir3 = new javax.swing.JLabel();
        tfDstDir3 = new javax.swing.JTextField();
        tfSrcDir3 = new javax.swing.JTextField();
        btnRecordSrcDir3 = new javax.swing.JButton();
        btnRecordDstDir3 = new javax.swing.JButton();
        btnRun3 = new javax.swing.JButton();
        lblSrcDir4 = new javax.swing.JLabel();
        lblDstDir4 = new javax.swing.JLabel();
        tfDstDir4 = new javax.swing.JTextField();
        tfSrcDir4 = new javax.swing.JTextField();
        btnRecordSrcDir4 = new javax.swing.JButton();
        btnRecordDstDir4 = new javax.swing.JButton();
        btnRun4 = new javax.swing.JButton();
        lblSrcDir0 = new javax.swing.JLabel();
        lblDstDir0 = new javax.swing.JLabel();
        tfDstDir0 = new javax.swing.JTextField();
        tfSrcDir0 = new javax.swing.JTextField();
        btnRecordSrcDir0 = new javax.swing.JButton();
        btnRecordDstDir0 = new javax.swing.JButton();
        btnRun0 = new javax.swing.JButton();
        lblSrcDir6 = new javax.swing.JLabel();
        lblDstDir6 = new javax.swing.JLabel();
        tfDstDir5 = new javax.swing.JTextField();
        tfSrcDir5 = new javax.swing.JTextField();
        btnRecordSrcDir5 = new javax.swing.JButton();
        btnRecordDstDir5 = new javax.swing.JButton();
        btnRun5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setName("mainFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        taConsole.setEditable(false);
        taConsole.setColumns(20);
        taConsole.setRows(5);
        jScrollPane1.setViewportView(taConsole);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 970, 140));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));
        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRunAll.setText("Hepsini Çalıştır");
        btnRunAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnRunAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 950, 30));

        lblSrcDir1.setText("kaynak 1:");
        jPanel1.add(lblSrcDir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 20));

        lblDstDir1.setText("hedef 1:");
        jPanel1.add(lblDstDir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 20));

        tfDstDir1.setEditable(false);
        tfDstDir1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.add(tfDstDir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 710, -1));

        tfSrcDir1.setEditable(false);
        tfSrcDir1.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.add(tfSrcDir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 710, -1));

        btnRecordSrcDir1.setText("Kayıt");
        btnRecordSrcDir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordSrcDir1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecordSrcDir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 70, -1));

        btnRecordDstDir1.setText("Kayıt");
        btnRecordDstDir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordDstDir1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecordDstDir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 70, -1));

        btnRun1.setText("Çalıştır");
        btnRun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRun1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRun1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, 80, 50));

        lblSrcDir2.setText("kaynak 2:");
        jPanel1.add(lblSrcDir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, 20));

        lblDstDir2.setText("hedef 2:");
        jPanel1.add(lblDstDir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 20));

        tfDstDir2.setEditable(false);
        tfDstDir2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.add(tfDstDir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 710, -1));

        tfSrcDir2.setEditable(false);
        tfSrcDir2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.add(tfSrcDir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 710, -1));

        btnRecordSrcDir2.setText("Kayıt");
        btnRecordSrcDir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordSrcDir2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecordSrcDir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 70, -1));

        btnRecordDstDir2.setText("Kayıt");
        btnRecordDstDir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordDstDir2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecordDstDir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 70, -1));

        btnRun2.setText("Çalıştır");
        btnRun2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRun2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRun2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 80, 50));

        lblSrcDir3.setText("kaynak 3:");
        jPanel1.add(lblSrcDir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 70, 20));

        lblDstDir3.setText("hedef 3:");
        jPanel1.add(lblDstDir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 70, 20));

        tfDstDir3.setEditable(false);
        tfDstDir3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.add(tfDstDir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 710, -1));

        tfSrcDir3.setEditable(false);
        tfSrcDir3.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.add(tfSrcDir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 710, -1));

        btnRecordSrcDir3.setText("Kayıt");
        btnRecordSrcDir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordSrcDir3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecordSrcDir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 70, -1));

        btnRecordDstDir3.setText("Kayıt");
        btnRecordDstDir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordDstDir3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecordDstDir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, 70, -1));

        btnRun3.setText("Çalıştır");
        btnRun3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRun3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRun3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 190, 80, 50));

        lblSrcDir4.setText("kaynak 4:");
        jPanel1.add(lblSrcDir4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 70, 20));

        lblDstDir4.setText("hedef 4:");
        jPanel1.add(lblDstDir4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 70, 20));

        tfDstDir4.setEditable(false);
        tfDstDir4.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.add(tfDstDir4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 710, -1));

        tfSrcDir4.setEditable(false);
        tfSrcDir4.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.add(tfSrcDir4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 710, -1));

        btnRecordSrcDir4.setText("Kayıt");
        btnRecordSrcDir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordSrcDir4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecordSrcDir4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 70, -1));

        btnRecordDstDir4.setText("Kayıt");
        btnRecordDstDir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordDstDir4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecordDstDir4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 70, -1));

        btnRun4.setText("Çalıştır");
        btnRun4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRun4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRun4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 80, 50));

        lblSrcDir0.setText("kaynak 0:");
        jPanel1.add(lblSrcDir0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        lblDstDir0.setText("hedef 0:");
        jPanel1.add(lblDstDir0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 20));

        tfDstDir0.setEditable(false);
        tfDstDir0.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.add(tfDstDir0, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 710, -1));

        tfSrcDir0.setEditable(false);
        tfSrcDir0.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.add(tfSrcDir0, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 710, -1));

        btnRecordSrcDir0.setText("Kayıt");
        btnRecordSrcDir0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordSrcDir0ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecordSrcDir0, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 70, -1));

        btnRecordDstDir0.setText("Kayıt");
        btnRecordDstDir0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordDstDir0ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecordDstDir0, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 70, -1));

        btnRun0.setText("Çalıştır");
        btnRun0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRun0ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRun0, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 80, 50));

        lblSrcDir6.setText("kaynak 5:");
        jPanel1.add(lblSrcDir6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 20));

        lblDstDir6.setText("hedef 5:");
        jPanel1.add(lblDstDir6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 70, 20));

        tfDstDir5.setEditable(false);
        tfDstDir5.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.add(tfDstDir5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 710, -1));

        tfSrcDir5.setEditable(false);
        tfSrcDir5.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.add(tfSrcDir5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 710, -1));

        btnRecordSrcDir5.setText("Kayıt");
        btnRecordSrcDir5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordSrcDir5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecordSrcDir5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, 70, -1));

        btnRecordDstDir5.setText("Kayıt");
        btnRecordDstDir5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordDstDir5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecordDstDir5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, 70, -1));

        btnRun5.setText("Çalıştır");
        btnRun5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRun5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRun5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, 80, 50));

        tb.addTab("Common", jPanel1);

        getContentPane().add(tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 970, 460));

        setSize(new java.awt.Dimension(1014, 660));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRunAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunAllActionPerformed
        MainRun.run_all();
    }//GEN-LAST:event_btnRunAllActionPerformed

    private void btnRecordSrcDir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordSrcDir1ActionPerformed
        MainRecordFolder.src_1();
    }//GEN-LAST:event_btnRecordSrcDir1ActionPerformed

    private void btnRecordDstDir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordDstDir1ActionPerformed
        MainRecordFolder.dst_1();
    }//GEN-LAST:event_btnRecordDstDir1ActionPerformed

    private void btnRun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRun1ActionPerformed
        MainRun.run_1();
    }//GEN-LAST:event_btnRun1ActionPerformed

    private void btnRecordSrcDir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordSrcDir2ActionPerformed
        MainRecordFolder.src_2();
    }//GEN-LAST:event_btnRecordSrcDir2ActionPerformed

    private void btnRecordDstDir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordDstDir2ActionPerformed
        MainRecordFolder.dst_2();
    }//GEN-LAST:event_btnRecordDstDir2ActionPerformed

    private void btnRun2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRun2ActionPerformed
        MainRun.run_2();
    }//GEN-LAST:event_btnRun2ActionPerformed

    private void btnRecordSrcDir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordSrcDir3ActionPerformed
        MainRecordFolder.src_3();
    }//GEN-LAST:event_btnRecordSrcDir3ActionPerformed

    private void btnRecordDstDir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordDstDir3ActionPerformed
        MainRecordFolder.dst_3();
    }//GEN-LAST:event_btnRecordDstDir3ActionPerformed

    private void btnRun3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRun3ActionPerformed
        MainRun.run_3();
    }//GEN-LAST:event_btnRun3ActionPerformed

    private void btnRecordSrcDir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordSrcDir4ActionPerformed
        MainRecordFolder.src_4();
    }//GEN-LAST:event_btnRecordSrcDir4ActionPerformed

    private void btnRecordDstDir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordDstDir4ActionPerformed
        MainRecordFolder.dst_4();
    }//GEN-LAST:event_btnRecordDstDir4ActionPerformed

    private void btnRun4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRun4ActionPerformed
        MainRun.run_4();
    }//GEN-LAST:event_btnRun4ActionPerformed

    private void btnRecordSrcDir0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordSrcDir0ActionPerformed
        MainRecordFolder.src_0();
    }//GEN-LAST:event_btnRecordSrcDir0ActionPerformed

    private void btnRecordDstDir0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordDstDir0ActionPerformed
        MainRecordFolder.dst_0();
    }//GEN-LAST:event_btnRecordDstDir0ActionPerformed

    private void btnRun0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRun0ActionPerformed
        MainRun.run_0();
    }//GEN-LAST:event_btnRun0ActionPerformed

    private void btnRecordSrcDir5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordSrcDir5ActionPerformed
        MainRecordFolder.src_5();
    }//GEN-LAST:event_btnRecordSrcDir5ActionPerformed

    private void btnRecordDstDir5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordDstDir5ActionPerformed
        MainRecordFolder.dst_5();
    }//GEN-LAST:event_btnRecordDstDir5ActionPerformed

    private void btnRun5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRun5ActionPerformed
        MainRun.run_5();
    }//GEN-LAST:event_btnRun5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecordDstDir0;
    private javax.swing.JButton btnRecordDstDir1;
    private javax.swing.JButton btnRecordDstDir2;
    private javax.swing.JButton btnRecordDstDir3;
    private javax.swing.JButton btnRecordDstDir4;
    private javax.swing.JButton btnRecordDstDir5;
    private javax.swing.JButton btnRecordSrcDir0;
    private javax.swing.JButton btnRecordSrcDir1;
    private javax.swing.JButton btnRecordSrcDir2;
    private javax.swing.JButton btnRecordSrcDir3;
    private javax.swing.JButton btnRecordSrcDir4;
    private javax.swing.JButton btnRecordSrcDir5;
    private javax.swing.JButton btnRun0;
    private javax.swing.JButton btnRun1;
    private javax.swing.JButton btnRun2;
    private javax.swing.JButton btnRun3;
    private javax.swing.JButton btnRun4;
    private javax.swing.JButton btnRun5;
    private javax.swing.JButton btnRunAll;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblDstDir0;
    private javax.swing.JLabel lblDstDir1;
    private javax.swing.JLabel lblDstDir2;
    private javax.swing.JLabel lblDstDir3;
    private javax.swing.JLabel lblDstDir4;
    private javax.swing.JLabel lblDstDir6;
    private javax.swing.JLabel lblSrcDir0;
    private javax.swing.JLabel lblSrcDir1;
    private javax.swing.JLabel lblSrcDir2;
    private javax.swing.JLabel lblSrcDir3;
    private javax.swing.JLabel lblSrcDir4;
    private javax.swing.JLabel lblSrcDir6;
    public javax.swing.JTextArea taConsole;
    public javax.swing.JTabbedPane tb;
    public javax.swing.JTextField tfDstDir0;
    public javax.swing.JTextField tfDstDir1;
    public javax.swing.JTextField tfDstDir2;
    public javax.swing.JTextField tfDstDir3;
    public javax.swing.JTextField tfDstDir4;
    public javax.swing.JTextField tfDstDir5;
    public javax.swing.JTextField tfSrcDir0;
    public javax.swing.JTextField tfSrcDir1;
    public javax.swing.JTextField tfSrcDir2;
    public javax.swing.JTextField tfSrcDir3;
    public javax.swing.JTextField tfSrcDir4;
    public javax.swing.JTextField tfSrcDir5;
    // End of variables declaration//GEN-END:variables
}
